
services:

  database:
    image: 'mysql:latest'
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env.local
    ports:
      - 3308:3306

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: database

  mailer:
    image: axllent/mailpit
    ports:
      - "1030:1025"  # SMTP
      - "8030:8025"  # Web UI (http://localhost:8025)

volumes:
  database:
