@startuml UserStoryAdminLightCone

left to right direction
skinparam actorFontStyle bold
skinparam usecase {
    BackgroundColor YellowGreen
    BorderColor Black
}

actor "Administrateur" as A #Red;text:Red

package "Gestion des cônes de lumière" {
    usecase "Ajouter cône de lumière" as Al #LightGray;text:Black
    usecase "Modifier cône de lumière" as Ml #LightGray;text:Black
    usecase "Supprimer cône de lumière" as Sl #LightGray;text:Black
}

' Relations entre acteurs et cas d'utilisation
A --> Al
A --> Ml
A --> Sl

' Description des cas d'utilisation
note right of Al
    En tant qu'administrateur, je veux pouvoir ajouter un cône de lumière.
end note
note right of Ml
    En tant qu'administrateur, je veux pouvoir modifier un cône de lumière.
end note
note right of Sl
    En tant qu'administrateur, je veux pouvoir supprimer un cône de lumière.
end note

@enduml