@startuml UserStoryModComment

left to right direction
skinparam actorFontStyle bold
skinparam usecase {
    BackgroundColor YellowGreen
    BorderColor Black
}

actor "Modérateur" as M #Orange;text:Orange

usecase "Supprimer commentaire" as Sc #LightGray;text:Black

' Relations entre acteurs et cas d'utilisation
M --> Sc

' Description des cas d'utilisation
note right of Sc
    En tant que modérateur, je veux pouvoir supprimer un commentaire d'un utilisateur.
end note

@enduml