@startuml DiagrammeActiviteAdminAddMaterial
title Diagramme d'activité pour l'ajout de matériel par un administrateur

|Admin|
start
:Accès au dashboard;
|Serveur|
if (Utilisateur est connecté et a le role admin ?) then (non)
  |Admin|
  #red: **Message d'erreur**;
  stop
else (oui)
  |Admin|
  :Accès à la section de gestion du matériel;
  :Ajouter un nouveau matériel;
  repeat
  :Remplir le formulaire d'ajout de matériel;
  |Serveur|
  :Vérification des données du formulaire;
  repeat while (Données valides?) is (non) not (oui)
    |Admin|
    :Validation des données;
    stop
  endif
@enduml