@startuml DiagrammeActiviteAdminDeleteRelic
title Diagramme d'activité pour la suppression d'un artefact par un administrateur

|Admin|
start
:Accès au dashboard;
|Serveur|
if (Utilisateur est connecté et a le role admin ?) then (non)
  |Admin|
  #red: **Message d'erreur**;
  stop
else (oui)
  |Admin|
  :Accès à la section de gestion des artefacts;
  :Sélectionner un artefact à supprimer;
  :Cliquer sur le bouton de suppression;
  |Serveur|
  :Vérification de la demande de suppression;
  if () is (si erreur) then
    |Admin|
    #red: **Message d'erreur**;
    stop
  else (si valide)
    |Serveur|
    :Demande de confirmation;
    |Admin|
    :Confirmer la suppression de l'artefact;
    |Serveur|
    :Suppression de l'artefact de la base de données;
    |Admin|
    :Afficher un message de succès;
    stop
  endif
  endif
@enduml