@startuml Inscription
title Inscription d'un utilisateur

|Utilisateur|
start
:Se rendre sur la page d'inscription;
:Entrer son adresse e-mail;
:Entrer son mot de passe;
:Confirmer son mot de passe;
:Accepter les conditions d'utilisation;
:Cliquer sur le bouton d'inscription;
|Serveur|
if (Adresse e-mail déjà utilisée?) then (oui)
  |Utilisateur|
  #red: **Message d'erreur**;
  stop
else (non)
  |Serveur|
  :Envoi du code de vérification par e-mail;
  |Utilisateur|
  :Entrer le code de vérification;
  |Serveur|
  if (Code de vérification valide?) then (non)
    |Utilisateur|
    #red: **Message d'erreur**;
    stop
  else (oui)
    |Utilisateur|
    :Inscription réussie;
    :Redirection;
    end
  endif
endif
@enduml